
const notes = [
    // H-NOTES
    {
        id: 1,
        type: "h-note",
        title: "SQL Basics",
        subject: "Database",
        format: "PDF",
        size: "4.4 MB",
        description: "Handwritten basic SQL notes covering queries, filtering, joins, and common syntax used in everyday database work.",
        fileUrl: "https://drive.google.com/file/d/1kPUYXw66G_rxoKwRVFVAxVh6N5nsnakE/view?usp=drive_link",
    },
    {
        id: 2,
        type: "h-note",
        title: "DBMS",
        subject: "Database",
        format: "PDF",
        size: "1.1 MB",
        description: "Handwritten DBMS notes covering normalization, indexing, transactions, recovery, and core database concepts.",
        fileUrl: "https://drive.google.com/file/d/1F_eXvvZ4WrDzVj-E1j_7H2i_z0yIh8VR/view?usp=drive_link",
    },
    {
        id: 3,
        type: "h-note",
        title: "API Quick Reference",
        subject: "Backend",
        format: "PDF",
        size: "12.6 MB",
        description: "Handwritten quick reference notes for APIs, request flow, response handling, and practical backend usage.",
        fileUrl: "https://drive.google.com/file/d/1u4tNK8xYUUGEKQH25ifltG8oDlOLMC9o/view?usp=drive_link",
    },
    {
        id: 4,
        type: "h-note",
        title: "ReactJS",
        subject: "Frontend",
        format: "PDF",
        size: "25 MB",
        description: "Handwritten ReactJS notes covering components, hooks, props, state, and common frontend patterns.",
        fileUrl: "https://drive.google.com/file/d/11-Fc9mbw_-KYi1PtohudDfvLPzEoINpf/view?usp=drive_link",
    },
    {
        id: 5,
        type: "h-note",
        title: "Node.js",
        subject: "Backend",
        format: "PDF",
        size: "735 KB",
        description: "Handwritten Node.js notes covering runtime basics, modules, server-side concepts, and backend fundamentals.",
        fileUrl: "https://drive.google.com/file/d/1X5sdf5hS4fhgc2c8fU49q5uvV528W2Z4/view?usp=drive_link",
    },
    {
        id: 6,
        type: "h-note",
        title: "More Handwritten Notes",
        subject: "Handwritten Notes",
        format: "Folder",
        size: "",
        description: "Folder containing additional handwritten notes and related reference material.",
        folderUrl: "https://drive.google.com/drive/folders/1APC7PpBrR4Q88cjGDeq2VT4BFklImrU_?usp=drive_link",
    },

    // CHEATSHEETS
    {
        id: 7,
        type: "cheatsheet",
        title: "Git Cheatsheet",
        subject: "Version Control",
        format: "PDF",
        size: "464 KB",
        description: "Compact Git reference covering commits, branches, merges, rebasing, and common version-control commands.",
        fileUrl: "https://drive.google.com/file/d/1xNjDRcnDzYCqWZs8FIb4tHV7-5PGsgUa/view?usp=drive_link",
    },
    {
        id: 8,
        type: "cheatsheet",
        title: "JavaScript",
        subject: "Frontend",
        format: "Folder",
        size: "",
        description: "Folder containing JavaScript cheatsheets, including dark mode and light mode versions.",
        folderUrl: "https://drive.google.com/drive/folders/1VFKaqNBn_ojI11y9HDQonhO1kzmcxhcq?usp=drive_link",
    },
    {
        id: 9,
        type: "cheatsheet",
        title: "HTML",
        subject: "Frontend",
        format: "Folder",
        size: "",
        description: "Folder containing HTML cheatsheets, including dark mode and light mode versions.",
        folderUrl: "https://drive.google.com/drive/folders/12YzdbSaWQAv13nE9YCkOQUFQRDKioRxw?usp=drive_link",
    },
    {
        id: 10,
        type: "cheatsheet",
        title: "More Cheatsheets",
        subject: "Cheatsheets",
        format: "Folder",
        size: "",
        description: "Folder containing the remaining cheatsheets and related reference files.",
        folderUrl: "https://drive.google.com/drive/folders/1ZpJ_AY0gtICKhdKE875fm1JHfDzqPOUH?usp=drive_link",
    },

    // MY-NOTES
    {
        id: 11,
        type: "my-note",
        title: "Spring Boot",
        subject: "Backend",
        format: "PDF",
        size: "36.9 MB",
        description: "Personal handwritten notes for Spring Boot covering application structure, REST APIs, and backend workflow.",
        fileUrl: "https://drive.google.com/file/d/1wnNej3lbxumErI5PVOJlCim-Xou8lVCp/view?usp=drive_link",
    },
    {
        id: 12,
        type: "my-note",
        title: "React",
        subject: "Frontend",
        format: "PDF",
        size: "20.9 MB",
        description: "Personal handwritten notes for React covering components, hooks, props, and practical frontend usage.",
        fileUrl: "https://drive.google.com/file/d/1F5PXodNKzld6M7OxAcXF31d0JZteHmv1/view?usp=drive_link",
    },
    {
        id: 13,
        type: "my-note",
        title: "More Personal Notes",
        subject: "My Notes",
        format: "Folder",
        size: "",
        description: "Folder containing the remaining personal notes and supporting material.",
        folderUrl: "https://drive.google.com/drive/folders/1J2fhMaHPqcifAfhBatm-VmquIyB75V2A?usp=drive_link",
    },

    // NOTES
    {
        id: 14,
        type: "note",
        title: "Java Programming Handbook",
        subject: "Java",
        format: "PDF",
        size: "1.1 MB",
        description: "Structured Java notes and handbook material for core Java concepts, syntax, and practice.",
        fileUrl: "https://drive.google.com/file/d/1F-jBwNcs1YVo2d_mj4tgiuo5t8_8PFO7/view?usp=drive_link",
    },
    {
        id: 15,
        type: "note",
        title: "Java Interview Questions",
        subject: "Java",
        format: "PDF",
        size: "138 KB",
        description: "Short Java interview question notes for fast revision and concept checking.",
        fileUrl: "https://drive.google.com/file/d/1credeKeue4pMBU_STf1LDIc98QmBfyIW/view?usp=drive_link",
    },
    {
        id: 16,
        type: "note",
        title: "More Notes",
        subject: "Notes",
        format: "Folder",
        size: "",
        description: "Folder containing the remaining notes and related documents.",
        folderUrl: "https://drive.google.com/drive/folders/1sMcx4mjrVlthYrfFUl9u_vo3NLaU2m1x?usp=drive_link",
    },

    // BOOKS
    {
        id: 17,
        type: "book",
        title: "Head First Java",
        subject: "Java",
        format: "PDF",
        size: "156 MB",
        description: "Java book for deep reading, concept building, and long-form study.",
        fileUrl: "https://drive.google.com/file/d/1kMWR2xaSVKXKxjgBbN-dHR0hL-RLU6z2/view?usp=drive_link",
    },
    {
        id: 18,
        type: "book",
        title: "More Books",
        subject: "Books",
        format: "Folder",
        size: "",
        description: "Folder containing additional books and reference material.",
        folderUrl: "https://drive.google.com/drive/folders/1LcWr_27sBz2L1cR1gkhUmOa9IRaZ9tMP?usp=drive_link",
    },
];

export default notes;