const projects = [
    {
      id: 1,
      title: "E-Commerce Platform",
      date: "Jan 2023 - Apr 2023",
      description: "Full-stack e-commerce solution with payment gateway integration",
      longDescription: "A comprehensive e-commerce platform supporting thousands of products with advanced search and filtering capabilities. Implemented secure payment processing and developed custom admin dashboard for inventory management.",
      technologies: ["React", "Node.js", "MongoDB", "Stripe API"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
    {
      id: 2,
      title: "AI Analytics Dashboard",
      date: "May 2023 - Aug 2023",
      description: "Machine learning-powered business intelligence dashboard",
      longDescription: "Real-time analytics platform using machine learning models to predict market trends. Features interactive data visualizations and custom reporting tools for business intelligence.",
      technologies: ["JavaScript", "React", "Tailwind", "Flask"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
    {
      id: 3,
      title: "Blockchain Voting System",
      date: "Sep 2023 - Present",
      description: "Decentralized voting application using smart contracts",
      longDescription: "Secure voting system built on blockchain ensuring transparency and immutability. Implements zero-knowledge proofs for voter anonymity and stores encrypted votes securely.",
      technologies: ["Solidity", "Web3.js", "Ethereum", "IPFS"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
    {
      id: 4,
      title: "Fitness Tracker App",
      date: "Mar 2023 - Jun 2023",
      description: "Mobile application for workout tracking and nutrition planning",
      longDescription: "Cross-platform fitness application with workout customization, progress tracking, and nutrition logging. Features include social sharing, achievement badges, and personalized recommendations.",
      technologies: ["React Native", "Firebase", "Redux", "Chart.js"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
    {
      id: 5,
      title: "Smart Home Dashboard",
      date: "Jul 2023 - Oct 2023",
      description: "IoT control panel for home automation systems",
      longDescription: "Centralized control system for IoT devices with real-time monitoring and automation rules. Supports voice commands and integrates with popular smart home ecosystems.",
      technologies: ["React", "EmailJs", "Javascript", "Sockets"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
    {
      id: 6,
      title: "Social Media Analytics",
      date: "Nov 2023 - Jan 2024",
      description: "Platform for tracking and analyzing social media performance",
      longDescription: "Comprehensive analytics suite for monitoring social media engagement, audience demographics, and content performance across multiple platforms with automated reporting.",
      technologies: ["Motion", "Tailwind", "MongoDB", "Nodejs"],
      imageUrl: "",
      demoLink: "#",
      codeLink: "#",
    },
  ];

  export default projects;